Story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('old/', include('old_profile_page.urls')),
    path('', include('profile_page.urls')),
]

old_profile_page/urls.py
from django.urls import path

from . import views

app_name = 'old_profile_page'

urlpatterns = [
    path('', views.index, name='index'),
]

profile_page/urls.py
from django.urls import path

from . import views

app_name = 'profile_page'

urlpatterns = [
    path('', views.index, name='index'),
    path('favicon.ico', views.index),
    path('mata-kuliah/', views.matkul, name='matkul'),
    path('mata-kuliah/hapus/<int:id>', views.matkul_hapus, name='matkul-hapus'),
    path('mata-kuliah/detail/<int:id>', views.matkul_detail, name='matkul-detail'),
    path('testimonials', views.testi, name='testi'),
    path('<str:gmt>', views.index_with_time, name='index_with_time'),
]

old_profile_page/models.py
from django.db import models

# Create your models here.

profile_page/models.py
from django.db import models
from django import forms
import datetime

# Create your models here.
class Matkul(models.Model) :
    SEMESTER_CHOICE = [
        ("Gasal", "Gasal"),
        ("Genap", "Genap"),
    ]
    TA_CHOICE = [
        ("2019/2020", "2019/2020"),
        ("2020/2021", "2020/2021"),
    ]
    id = models.AutoField(primary_key=True)
    nama = models.CharField(max_length=32, blank=False)
    dosen = models.CharField(max_length=32, blank=False)
    sks = models.IntegerField(blank=False)
    deskripsi = models.TextField(blank=True)
    semester = models.CharField(max_length=32, choices=SEMESTER_CHOICE, default="Gasal")
    tahun_ajaran = models.CharField(max_length=32, choices=TA_CHOICE, default="2019/2020")
    ruang = models.CharField(max_length=16, blank=False)

    def __str__(self):
        return self.nama

class Task(models.Model) :
    nama = models.CharField(max_length=32)
    desc = models.TextField(blank=True)
    deadline = models.DateTimeField()
    matkul = models.ForeignKey(Matkul, on_delete=models.CASCADE)

    def __str__(self):
        return self.nama

    def color(self):
        deadline = self.deadline
        now = datetime.datetime.now(datetime.timezone.utc)
        difference = (deadline - now).days
        color = "0000"
        if(difference < 0) : color = "#444444"
        else : color = "#" + hex(150 + difference*2)[2:] + color
        
        return color

    class Meta :
        ordering = ['deadline']

profile_page/forms.py
from django import forms  
from .models import Matkul

class MatkulForm(forms.ModelForm) :
    class Meta :
        model = Matkul
        fields = '__all__'
        exclude = ['id']

old_profile_page/views.py
from django.shortcuts import render

# Create your views here.
def index(request) :
    return render(request, "old_profile_page/index.html")

profile_page/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import MatkulForm
from .models import *
from django.shortcuts import get_list_or_404, get_object_or_404, redirect
from django.urls import reverse
import datetime

def index(request) :
    now = datetime.datetime.now()
    time = {
        "now" : now.strftime("%H:%M")
    }
    return render(request, "profile_page/index.html", context=time)

def index_with_time(request, gmt) :
    gmt = int(gmt)
    now = datetime.datetime.now()
    hour = (now.hour + gmt) % 24
    now = now.replace(hour = hour)
    time = {
        "now" : now.strftime("%H:%M"),
    }
    return render(request, "profile_page/index.html", context=time)

def testi(request) :
    return render(request, "profile_page/testimonials.html")

def matkul(request) :
    if(request.method == "POST") :
        matkul_form = MatkulForm(request.POST)

        if(matkul_form.is_valid) :
            matkul_form.save()
        
        else :
            print(matkul_form.errors)

    matkul_form = MatkulForm()
    data = Matkul.objects.all()

    return render(request, "profile_page/matkul.html", {"form":matkul_form, "data":data})

def matkul_detail(request, id) :
    data = Matkul.objects.get(id=id)
    tasks = Task.objects.all().filter(matkul=data)

    return render(request, "profile_page/matkul-detail.html", {"item" : data, "tasks" : tasks})

def matkul_hapus(request, id) :
    tmp_obj = get_object_or_404(Matkul, id=id)
    try :
        tmp_obj.delete()
    except :
        pass
    
    return redirect("/mata-kuliah/")

old_profile_page/templates/old_profile_page/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Profile Aldi</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static 'old_profile_page/style.css' %}">
</head>
<body data-spy="scroll" data-target=".navbar">
  <div id="jumbotron" class="jumbotron jumbotron-fluid mb-0">
    <div class="container mx-auto my-auto" style="width: 700px;">
      <h1 id="header-text" class="display-4 text-center text-white">A l d i &nbsp N a u f a l &nbsp F i t r a h</h1>
      <p class="blockquote text-center mt-4 mb-0" style="color: darkgrey;">Tak kenal maka tak sayang...</p>
      <footer class="blockquote-footer text-right" style="margin-right: 31.5%;">Pepatah</footer>
      <a href="#about"><img id="scroll-down" class="mx-auto d-block" src="{% static 'old_profile_page/img/scroll-down.png' %}" alt="" width="50px"></a>
    </div>

  </div>

  <nav class="navbar navbar-expand-xl bg-dark navbar-dark sticky-top">
    <!-- Brand -->
    <a id="navbrand" class="navbar-brand ml-4 mt-2" href="#jumbotron">Aldi</a>
  
    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <!-- Navbar links -->
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav mr-5 ml-auto">
        <li class="nav-item mx-3">
          <a class="nav-link" href="#about">About</a>
        </li>
        <li class="nav-item mx-3">
          <a class="nav-link" href="#profile">Education</a>
        </li>
        <li class="nav-item mx-3">
          <a class="nav-link" href="#contact">Contact</a>
        </li>
      </ul>
    </div>
  </nav>

  <div id="about" class="anchor">
    <img id="foto" src="{% static 'old_profile_page/img/ID03-min2.jpg' %}" alt="Foto Aldi">
    <div id="teks" class="mr-5">
      <h3 class="display-3" style="font-weight: bold; font-family: Helvetica;">Hai, nama saya Aldi!</h3><br>
      <p id="deskripsi" class="lead">Saya adalah saya, bukan dia, apalagi mereka. Di masa depan, saya akan menjadi saya yang lebih baik dari hari ini, baik dari segi kedewasaan, finansial, juga pemikiran. Di waktu senggang, saya suka membuka laptop untuk sekadar mendengarkan musik dan mencari sesuatu untuk dikerjakan, atau berbincang kepada orang-orang terdekat. Ini tentang saya, jadi nikmati saja ya.</p>
  </div>
  </div>
  
  <div id="profile" class="anchor ml-3 mt-n4">
    <div id="pendidikan">
      <h2 class="display-3" style="font-weight: 500;">Riwayat Pendidikan</h2>
      <ul>
        <li>
          <div class="sekolah-wrapper">
            <h5>2005 - 2007</h5>
            <h4>TK Putradarma Global School Tambun Selatan</h4>
            <img class="logo-sekolah" src="{% static 'old_profile_page/img/pdgs.png' %}" alt="Putradarma Global School">
          </div>
        </li>
        <li>
          <div class="sekolah-wrapper">
            <h5>2007 - 2008</h5>
            <h4>SDN 03 Alai Padang</h4>
            <img class="logo-sekolah" src="{% static 'old_profile_page/img/tut-wuri-handayani.png' %}" alt="">
          </div>
        </li>
        <li>
          <div class="sekolah-wrapper">
            <h5>2008 - 2009</h5>
            <h4>SDN Mekarsari 01 Tambun Selatan</h4>
            <img class="logo-sekolah" src="{% static 'old_profile_page/img/tut-wuri-handayani.png' %}" alt="">
          </div>
        </li>
        <li>
          <div class="sekolah-wrapper">
            <h5>2012 - 2013</h5>
            <h4>SDN Jemurwonosari 1 Surabaya</h4>
            <img class="logo-sekolah" src="{% static 'old_profile_page/img/tut-wuri-handayani.png' %}" alt="">
          </div>
        </li>
        <li>
          <div class="sekolah-wrapper">
            <h5>2009 - 2012</h5>
            <h4>SDN 6 Pekanbaru</h4>
            <img class="logo-sekolah" src="{% static 'old_profile_page/img/tut-wuri-handayani.png' %}" alt="">
          </div>
        </li>
        <li>
          <div class="sekolah-wrapper">
            <h5>2013 - 2016</h5>
            <h4>SMPN 1 Medan</h4>
            <img class="logo-sekolah" src="{% static 'old_profile_page/img/tut-wuri-handayani.png' %}" alt="">
          </div>
        </li>
        <li>
          <div class="sekolah-wrapper">
            <h5>2016 - 2019</h5>
            <h4>SMAN 1 Matauli Pandan</h4>
            <img class="logo-sekolah" src="{% static 'old_profile_page/img/mtn.png' %}" alt="Matauli">
          </div>
        </li>
        <li>
          <div>
            <div class="sekolah-wrapper">
              <h5>2019 - sekarang</h5>
              <h4>Universitas Indonesia</h4>
              <img class="logo-sekolah" src="{% static 'old_profile_page/img/pacil.png' %}" alt="Fasilkom UI">
            </div>
          </div>
          <button id="detail-button" class="btn btn-primary fluid" type="button" data-toggle="collapse" data-target="#detail" aria-expanded="false" aria-controls="detail">
            Detail
          </button>
          <div class="collapse" id="detail" style="font-weight: 600; padding-left: 30px;">
            <table>
              <tr>
                <td>NPM :</td>
                <td>1906285472</td>
              </tr>
              <tr>
                <td>Angkatan :</td>
                <td><a href="https://maung.id/" target="_blank"><img id="logo-maung" src="{% static 'old_profile_page/img/maung-nav.png' %}" alt="maung 2019"></a></td>
              </tr>
            </table>
          </div>
        </li>
      </ul>
    </div>
  </div>

  <div id="contact" class="anchor mx-auto my-4" style="width: 400px;">
    <h6 class="display-6">Contact me at:</h6>
    <a target="_blank" href="http://line.me/ti/p/~aldinfitrah"><img src="{% static 'old_profile_page/img/line.png' %}" alt="Logo Line"></a>
    <a target="_blank" href="https://www.instagram.com/aldinfitrah/"><img src="{% static 'old_profile_page/img/instagram.jpg' %}" alt="Logo Line"></a>
    <a target="_blank" href="https://www.linkedin.com/in/aldi-naufal-fitrah-645ba4175"><img src="{% static 'old_profile_page/img/linkedin.png' %}" alt="Logo Line"></a>
    <a target="_blank" href="https://wa.me/6281381136428?text=Hai%20Aldi,%20nama%20saya%20"><img src="{% static 'old_profile_page/img/whatsapp.jpg' %}" alt="Logo Line"></a>
  </div>
  
  <!-- by Joseph Silber -->
  <!-- Got it from https://stackoverflow.com/questions/7717527/smooth-scrolling-when-clicking-an-anchor-link -->
  <script>
    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
      anchor.addEventListener('click', function (e) {
        e.preventDefault();

        document.querySelector(this.getAttribute('href')).scrollIntoView({
          behavior: 'smooth'
        });
      });
    });
  </script>
</body>
</html>

profile_page/templates/profile_page/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Quantico&display=swap" rel="stylesheet">
  <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'profile_page/style.css' %}">
	<title>Story 4 PPW</title>
</head>
<body data-spy="scroll" data-target=".navbar">

  <h6 style="position:fixed; z-index: 10;">{{ now }}</h6>
  {% block content %}
  {% endblock %}

  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
  
  <!-- by Joseph Silber -->
  <!-- Got it from https://stackoverflow.com/questions/7717527/smooth-scrolling-when-clicking-an-anchor-link -->
  <script>
    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
      anchor.addEventListener('click', function (e) {
        e.preventDefault();

        document.querySelector(this.getAttribute('href')).scrollIntoView({
          behavior: 'smooth'
        });
      });
    });
    AOS.init();
  </script>
</body>
</html>

profile_page/templates/profile_page/matkul-detail.html
{% extends 'profile_page/base.html' %}

{% block content %}
  {% include 'profile_page/navbar.html' %}
  <table>
    <tr>
      <th>Nama Mata Kuliah</th>
      <td>: {{ item.nama }}</td>
    </tr>
    <tr>
      <th>Dosen</th>
      <td>: {{ item.dosen }}</td>
    </tr>
    <tr>
      <th>Jumlah SKS</th>
      <td>: {{ item.sks }}</td>
    </tr>
    <tr>
      <th>Ruangan</th>
      <td>: {{ item.ruang }}</td>
    </tr>
    <tr>
      <th>Semester</th>
      <td>: {{ item.semester }}</td>
    </tr>
    <tr>
      <th>Tahun Ajaran</th>
      <td>: {{ item.tahun_ajaran }}</td>
    </tr>
    <tr>
      <th>Deskripsi</th>
      <td>: {{ item.deskripsi }}</td>
    </tr>
    <tr>
      <td><a href="{% url 'profile_page:matkul' %}"><button class="btn btn-primary">Back</button></a></td>
      <td><a href="{% url 'profile_page:matkul-hapus' item.id %}"><button class="btn btn-danger">Delete</button></a></td>
    </tr>
  </table>
  <div>
    <h3>Tugas-Tugas</h3>
    <table style="border: 2px solid white;">
      <tr>
        <th>Nama</th>
        <th>Deskripsi</th>
        <th>Deadline</th>
      </tr>
      {% for task in tasks %}
        <tr style="background-color: {{ task.color }};">
          <td>{{ task.nama }}</td>
          <td>{{ task.desc }}</td>
          <td>{{ task.deadline }}</td>
        </tr>
      {% endfor %}
    </table>
  </div>
{% endblock %}

profile_page/templates/profile_page/matkul.html
{% extends 'profile_page/base.html' %}

{% block content %}
  {% include 'profile_page/navbar.html' %}
  <div class="matkul d-flex flex-row">

    <div class="matkul-form">
      <form action="" method="post">
        <table>
          {% csrf_token %}
          {% for field in form %}
            <tr>
              <td>{{ field.label }}</td>
              <td>{{ field }}</td>
            </tr>      
          {% endfor %}
        </table>
        <button type="submit">Submit!</button>
      </form>
    </div>

    <div class="matkul-data">
      <table>
        <tr>
          <th>Nama Mata Kuliah</th>
          <th>Ruangan</th>
          <th>Detail</th>
          <th>Delete</th>
        </tr>
        {% for item in data %}
          <tr>
            <td>{{ item.nama }}</td>
            <td>{{ item.ruang }}</td>
            <td><a href="{% url 'profile_page:matkul-detail' item.id %}"><button type="button" class="btn btn-primary">Detail</button></a></td>
            <td><a href="{% url 'profile_page:matkul-hapus' item.id %}"><button type="button" class="btn btn-danger">Delete</button></a></td>
          </tr>
        {% endfor %}
      </table>
    </div>

  </div>
{% endblock %}

profile_page/templates/profile_page/navbar.html
<nav id="navbar" class="navbar navbar-expand-lg sticky-top navbar-dark" style="z-index: 2;">
  <!-- Brand -->
  <a id="navbrand" class="navbar-brand ml-4 mt-2" href="{% url 'profile_page:index' %}#jumbotron">Aldi</a>
  
  <!-- Toggler/collapsibe Button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <!-- Navbar links -->
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav mr-3 ml-auto">
      <li class="nav-item mx-3">
        <a class="nav-link" href="{% url 'profile_page:index' %}#about" target="_self">About</a>
      </li>
      <li class="nav-item mx-3">
        <a class="nav-link" href="{% url 'profile_page:index' %}#education" target="_self">Education</a>
      </li>
      <li class="nav-item mx-3">
        <a class="nav-link" href="{% url 'profile_page:index' %}#achievement" target="_self">Achievement</a>
      </li>
      <li class="nav-item mx-3">
        <a class="nav-link" href="{% url 'profile_page:index' %}#project" target="_self">Project</a>
      </li>
      <li class="nav-item mx-3">
        <a class="nav-link" href="{% url 'profile_page:index' %}#contact" target="_self">Contact</a>
      </li>
      <li class="nav-item mx-3">
        <a class="nav-link" href="{% url 'profile_page:testi' %}#testimonials" target="_self">Testimoni</a>
      </li>
      <li class="nav-item dropdown mx-3">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Etc
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'old_profile_page:index' %}">Story 1 PPW</a>
          <a class="dropdown-item" href="{% url 'profile_page:matkul' %}">Mata Kuliah</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

profile_page/templates/profile_page/testimonials.html
{% extends 'profile_page/base.html' %}
{% load static %}

{% block content %}
  {% include 'profile_page/navbar.html' %}

  <div id="testimonials" class="anchor">
    <h2 class="display-4">Testimonials</h2>
    <div class="testi-item d-flex flex-row" data-aos="fade-right">
      <div class="left-section">
        <img src="{% static 'profile_page/img/profpic1.jpg' %}" alt="">
      </div>
      <div class="right-section">
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore tenetur molestiae doloremque dignissimos quaerat rerum doloribus deleniti similique pariatur, nam neque excepturi eos exercitationem. Ipsum minima reprehenderit amet molestias culpa? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nam recusandae illo error minima sed, eaque porro quaerat nemo cum quod assumenda magnam repellat. Doloremque voluptates nemo numquam aperiam delectus facilis.
      </div>
    </div>
    <div class="testi-item d-flex flex-row" data-aos="fade-right">
      <div class="left-section">
        <img src="{% static 'profile_page/img/profpic2.jpg' %}" alt="">
      </div>
      <div class="right-section">
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore tenetur molestiae doloremque dignissimos quaerat rerum doloribus deleniti similique pariatur, nam neque excepturi eos exercitationem. Ipsum minima reprehenderit amet molestias culpa? Lorem ipsum, dolor sit amet consectetur adipisicing elit. Hic eveniet nesciunt esse repellat id! Magni ipsum, animi, ut molestias culpa exercitationem dolore maiores dolorem est debitis doloribus atque sunt velit.
      </div>
    </div>
    <div class="testi-item d-flex flex-row" data-aos="fade-right">
      <div class="left-section">
        <img src="{% static 'profile_page/img/profpic3.jpg' %}" alt="">
      </div>
      <div class="right-section">
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore tenetur molestiae doloremque dignissimos quaerat rerum doloribus deleniti similique pariatur, nam neque excepturi eos exercitationem. Ipsum minima reprehenderit amet molestias culpa? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis, fugiat, et accusantium explicabo sint voluptas repudiandae voluptatem, molestias esse suscipit est vero sit deserunt magni perferendis! Quasi quod tempore et!
      </div>
    </div>
    <div class="testi-item d-flex flex-row" data-aos="fade-right">
      <div class="left-section">
        <img src="{% static 'profile_page/img/profpic4.jpg' %}" alt="">
      </div>
      <div class="right-section">
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore tenetur molestiae doloremque dignissimos quaerat rerum doloribus deleniti similique pariatur, nam neque excepturi eos exercitationem. Ipsum minima reprehenderit amet molestias culpa? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro, placeat aspernatur debitis asperiores ipsum amet ad expedita id. Recusandae consequatur corporis incidunt maiores voluptates, exercitationem et nisi earum ipsam provident?
      </div>
    </div>
    <div class="testi-item d-flex flex-row" data-aos="fade-right">
      <div class="left-section">
        <img src="{% static 'profile_page/img/profpic5.jpg' %}" alt="">
      </div>
      <div class="right-section">
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore tenetur molestiae doloremque dignissimos quaerat rerum doloribus deleniti similique pariatur, nam neque excepturi eos exercitationem. Ipsum minima reprehenderit amet molestias culpa? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officiis commodi, culpa similique ea omnis eos ducimus consequatur ad at eveniet quo beatae facere, dolorem veniam maxime exercitationem, ipsum tenetur modi.
      </div>
    </div>
  </div>
{% endblock %}